spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/megatouch_db
    username: mega
    password: touch
  flyway:
    user: mega
    password: touch
server:
  port: 9090
keycloak:
  keySet: http://localhost:8080/realms/megatouch/protocol/openid-connect/certs